Repository Jonxslays/wom.py, pull requests merged in 2023-05, with the labels that each got.

#17 Fix support for python 3.8 and 3.9
  .github/workflows/ci.yml
  tests/test_serializer.py
  wom/client.py
  wom/enums.py
  wom/models/base.py
  wom/models/competitions/models.py
  wom/models/groups/models.py
  wom/models/names/models.py
  wom/models/players/models.py
  wom/routes.py
  wom/serializer.py
  wom/services/base.py
  wom/services/competitions.py
  wom/services/deltas.py
  wom/services/efficiency.py
  wom/services/groups.py
  wom/services/http.py
  wom/services/names.py
  wom/services/players.py
  wom/services/records.py
Labels: bug

#18 Add support for review context on name changes
  CHANGELOG.md
  tests/test_serializer.py
  wom/__init__.py
  wom/models/__init__.py
  wom/models/names/__init__.py
  wom/models/names/enums.py
  wom/models/names/models.py
  wom/serializer.py
  wom/services/competitions.py
Labels: enhancement

#19 Update enums.py bosses to align more closely with the wom api.
  wom/enums.py
Labels: bug, breaking
